CREATE TABLE AAVV (`subdistrict_id` INT PRIMARY KEY, `subdistrict` VARCHAR(100), `district_id` INT NOT NULL);

INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (1, 'Albayzin', 1);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (2, 'Almanjayar', 6);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (3, 'Barriada de la Cruz', 2);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (4, 'Bobadilla', 4);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (5, 'Bola de Oro', 5);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (6, 'Camino de los Neveros', 5);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (7, 'Camino de Ronda', 7);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (8, 'Campo Verde', 6);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (9, 'Carretera de la Sierra', 5);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (10, 'Cartuja', 6);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (11, 'Caseria de Montijo', 6);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (12, 'Castaño - Mirasierra', 5);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (13, 'Centro - Sagrario', 3);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (14, 'Cerrillo de Maracena', 4);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (15, 'Cervantes', 5);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (16, 'Chana - Encina - Angustias', 4);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (17, 'Doctores - Plaza de Toros', 2);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (18, 'El Fargue', 1);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (19, 'Figares', 7);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (20, 'Haza Grande', 1);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (21, 'Joaquina Eguaras', 2);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (22, 'La Paz', 6);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (23, 'Lancha del Genil', 5);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (24, 'Pajaritos', 2);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (25, 'Parque de la Rosaleda', 7);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (26, 'Parque Nueva Granada', 6);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (27, 'Realejo - San Matias', 3);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (28, 'Rey Badis', 6);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (29, 'Sacromonte', 1);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (30, 'San Francisco Javier', 2);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (31, 'San Ildefonso', 2);
INSERT INTO `aavv` (`Id_AAVV`, `Nombre`, `Id_distrito`) VALUES (32, 'Zaidin - Vergeles', 8);
